CC=g++

all:SimpleChat

SimpleChat:
	g++ -o SimpleChat main.cpp SimpleChat.h SimpleChat.cpp SimpleMessage.h SimpleMessage.cpp SimpleUtility.h SimpleUtility.cpp -std=c++11

.PHONY:clean

clean:
	-rm SimpleChat

