CC=g++

all:SimpleChat

SimpleChat:
	g++ -o SimpleChat main.cpp simpleChat.h simpleChat.cpp simpleMessage.h simpleMessage.cpp SimpleUtility.h SimpleUtility.cpp -std=c++11

.PHONY:clean

clean:
	-rm SimpleChat

